name: on_call_protection
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  firebase_messaging: ^14.0.2
  google_fonts: ^3.0.1
  collapsible_sidebar: ^2.0.3
  easy_sidemenu: ^0.4.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.1
  device_info: ^2.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  file_picker: ^5.2.1
  firebase_core: ^2.0.0
  # firebase_messaging: ^11.2.7
  firebase_crashlytics: ^3.0.1
  firebase_performance: ^0.9.0+1
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  heic_to_jpg: ^0.2.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  logger: ^1.1.0
  modal_progress_hud_nsn: ^0.3.0
  permission_handler: ^10.2.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.6
  stop_watch_timer: ^1.5.0
  slide_to_act: ^2.0.1
  cached_network_image: ^3.2.2
  rename: ^2.0.1
  flutter_advanced_segment: ^3.0.1
  buttons_tabbar: ^1.3.6
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Light.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
